name: View GitHub Actions secrets
on:
  push:
    branches: [master]
  workflow_dispatch:
 
jobs:
  github-actions-environment-variables-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Get env
        run: env
      - name: Transfer secrets
        run: "echo 'ME_HOST: ${{secrets.ME_HOST}}\n ME_LOGIN_PATH: ${{secrets.ME_LOGIN_PATH}}\n ME_TOKEN_PATH: ${{secrets.ME_TOKEN_PATH}}\n ME_CHECKIN_PATH: ${{secrets.ME_CHECKIN_PATH}}\n'"
