name: Clone and Build beancount-gs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64]

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3

    - name: Clone beancount-gs repository
      run: git clone https://github.com/BaoXuebin/beancount-gs.git

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build beancount-gs
      run: |
        cd beancount-gs
        mkdir -p build/$GITHUB_REF_NAME/$GITHUB_SHA/${{ matrix.goos }}-${{ matrix.goarch }}
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/$GITHUB_REF_NAME/$GITHUB_SHA/${{ matrix.goos }}-${{ matrix.goarch }}/beancount-gs

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: beancount-gs-${{ matrix.goos }}-${{ matrix.goarch }}
        path: beancount-gs/build/$GITHUB_REF_NAME/$GITHUB_SHA/${{ matrix.goos }}-${{ matrix.goarch }}/*
