name: me-1_checkin_2

on:
  schedule:
    - cron: "0 4,12 * * *"
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: lentikr/me-1_checkin@main
        with:
          username: ${{ secrets.ME_USERNAME_2 }}
          passwd: ${{ secrets.ME_PASSWD_2 }}
          host: ${{ secrets.ME_HOST }}
          login_path: ${{ secrets.ME_LOGIN_PATH }}
          token_path: ${{ secrets.ME_TOKEN_PATH }}
          checkin_path: ${{ secrets.ME_CHECKIN_PATH }}
